"""Add currency field to bank account

Revision ID: 7a55ad7e9a9b
Revises: b83f668f7ed8
Create Date: 2024-09-05 22:42:23.978036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a55ad7e9a9b'
down_revision = 'b83f668f7ed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_accounts', sa.Column('currency', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_accounts', 'currency')
    # ### end Alembic commands ###
